FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Create empty migration files for all apps
RUN mkdir -p accounts/migrations && \
    touch accounts/migrations/__init__.py && \
    python manage.py makemigrations accounts --empty --name initial

# Create migrations for other apps
RUN python manage.py makemigrations announcements business core inventory notifications reports sales shifts

CMD ["python", "manage.py", "migrate"]
