
version: '3'

services:
  db:
    container_name: backend-db-1
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fruitpos
      POSTGRES_USER: fruitpos_user
      POSTGRES_PASSWORD: fruitpos_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: backend-redis-1
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  api:
    container_name: backend-api-1
    build: .
    command: ["/app/docker-entrypoint.sh", "daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      POSTGRES_DB: fruitpos
      POSTGRES_USER: fruitpos_user
      POSTGRES_PASSWORD: fruitpos_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0

  nginx:
    container_name: backend-nginx-1
    image: nginx:1.25
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
    depends_on:
      - api

volumes:
  postgres_data:
