# Generated by Django 5.2.3 on 2025-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalcustomuser_historicalperfil_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperfil',
            name='business',
        ),
        migrations.RemoveField(
            model_name='historicalperfil',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalperfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluserrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='historicaluserrole',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserrole',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='second last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='tax ID'),
        ),
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
        migrations.DeleteModel(
            name='HistoricalPerfil',
        ),
        migrations.DeleteModel(
            name='HistoricalUserRole',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
