# Generated by Django 5.2.3 on 2025-07-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_historicalperfil_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones', models.BooleanField(default=True)),
                ('privacidad', models.BooleanField(default=True)),
                ('estilo_aplicacion', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=20)),
                ('color_aplicacion', models.CharField(choices=[('inherit', 'Inherit'), ('current', 'Current'), ('transparent', 'Transparent'), ('black', 'Black'), ('white', 'White'), ('zinc', 'Zinc'), ('red', 'Red'), ('darkred', 'Dark Red'), ('tomato', 'Tomato'), ('salmon', 'Salmon'), ('orange', 'Orange'), ('gold', 'Gold'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('darkgreen', 'Dark Green'), ('turquoise', 'Turquoise'), ('cyan', 'Cyan'), ('skyblue', 'Sky Blue'), ('blue', 'Blue'), ('navy', 'Navy'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('magenta', 'Magenta'), ('pink', 'Pink'), ('crimson', 'Crimson'), ('amber', 'Ambar'), ('emerald', 'Esmeralda'), ('violet', 'Violeta')], default='white', max_length=20)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='accounts.perfil')),
            ],
        ),
    ]
