# Generated by Django 5.2.5 on 2025-08-07 03:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=16)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_diferencia', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_abre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift',
                'verbose_name_plural': 'historical shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=16)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_diferencia', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('usuario_abre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_abiertos', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalShiftExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('descripcion', models.CharField(help_text='Descripción del gasto', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte'), ('insumos', 'Insumos'), ('servicios', 'Servicios'), ('personal', 'Personal'), ('mantenimiento', 'Mantenimiento'), ('impuestos', 'Impuestos'), ('otros', 'Otros')], default='otros', help_text='Categoría del gasto', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('otro', 'Otro')], default='efectivo', help_text='Método de pago utilizado', max_length=20)),
                ('comprobante', models.TextField(blank=True, help_text='Imagen o PDF del comprobante', max_length=100, null=True)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de factura o boleta', max_length=50)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor o beneficiario', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del gasto')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el gasto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autorizado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que autorizó el gasto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que registró el gasto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'historical Gasto de Turno',
                'verbose_name_plural': 'historical Gastos de Turno',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBoxRefill',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('cantidad_cajas', models.PositiveIntegerField(help_text='Cantidad de cajas descontadas por relleno')),
                ('motivo', models.TextField(help_text='Motivo del descuento de cajas')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('fruit_lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.fruitlot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'historical Relleno de Cajas',
                'verbose_name_plural': 'historical Rellenos de Cajas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BoxRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_cajas', models.PositiveIntegerField(help_text='Cantidad de cajas descontadas por relleno')),
                ('motivo', models.TextField(help_text='Motivo del descuento de cajas')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('fruit_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_refills', to='inventory.fruitlot')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_refills', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Relleno de Cajas',
                'verbose_name_plural': 'Rellenos de Cajas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ShiftExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(help_text='Descripción del gasto', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte'), ('insumos', 'Insumos'), ('servicios', 'Servicios'), ('personal', 'Personal'), ('mantenimiento', 'Mantenimiento'), ('impuestos', 'Impuestos'), ('otros', 'Otros')], default='otros', help_text='Categoría del gasto', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('otro', 'Otro')], default='efectivo', help_text='Método de pago utilizado', max_length=20)),
                ('comprobante', models.FileField(blank=True, help_text='Imagen o PDF del comprobante', null=True, upload_to='comprobantes_gastos/')),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de factura o boleta', max_length=50)),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor o beneficiario', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del gasto')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el gasto')),
                ('autorizado_por', models.ForeignKey(help_text='Usuario que autorizó el gasto', on_delete=django.db.models.deletion.CASCADE, related_name='gastos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el gasto', on_delete=django.db.models.deletion.CASCADE, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Gasto de Turno',
                'verbose_name_plural': 'Gastos de Turno',
                'ordering': ['-fecha'],
            },
        ),
    ]
