# Generated by Django 5.2.3 on 2025-07-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_historicalshift_uid_shift_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshift',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='uid',
        ),
    ]
