# Generated by Django 5.2.3 on 2025-06-22 18:39

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='en_proceso', max_length=16)),
                ('timeout_minutos', models.PositiveIntegerField(default=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical stock reservation',
                'verbose_name_plural': 'historical stock reservations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MadurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_maduracion', models.CharField(choices=[('verde', 'Verde'), ('pre-maduro', 'Pre-maduro'), ('maduro', 'Maduro'), ('sobremaduro', 'Sobremaduro')], max_length=16)),
                ('fecha_cambio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('peso_pallet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('unidad', models.CharField(default='caja', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='en_proceso', max_length=16)),
                ('timeout_minutos', models.PositiveIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True)),
                ('peso_caja', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_pallet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='FruitLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('proveedor', models.CharField(max_length=64)),
                ('procedencia', models.CharField(max_length=64)),
                ('pais', models.CharField(max_length=32)),
                ('calibre', models.CharField(max_length=16)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qr_code', models.CharField(max_length=128, unique=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('estado_maduracion', models.CharField(choices=[('verde', 'Verde'), ('pre-maduro', 'Pre-maduro'), ('maduro', 'Maduro'), ('sobremaduro', 'Sobremaduro')], default='verde', max_length=16)),
                ('fecha_maduracion', models.DateField(blank=True, null=True)),
                ('porcentaje_perdida_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_diario_almacenaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxtype')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFruitLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('proveedor', models.CharField(max_length=64)),
                ('procedencia', models.CharField(max_length=64)),
                ('pais', models.CharField(max_length=32)),
                ('calibre', models.CharField(max_length=16)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qr_code', models.CharField(db_index=True, max_length=128)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('estado_maduracion', models.CharField(choices=[('verde', 'Verde'), ('pre-maduro', 'Pre-maduro'), ('maduro', 'Maduro'), ('sobremaduro', 'Sobremaduro')], default='verde', max_length=16)),
                ('fecha_maduracion', models.DateField(blank=True, null=True)),
                ('porcentaje_perdida_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_diario_almacenaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('box_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.boxtype')),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fruit lot',
                'verbose_name_plural': 'historical fruit lots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('unidad', models.CharField(default='caja', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
