# Generated by Django 5.2.3 on 2025-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_boxtype_uid_fruitlot_uid_goodsreception_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreception',
            name='numero_guia',
            field=models.CharField(blank=True, help_text='Número de guía interna', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgoodsreception',
            name='numero_guia',
            field=models.CharField(blank=True, db_index=True, help_text='Número de guía interna', max_length=50, null=True),
        ),
    ]
