# Generated by Django 5.2.3 on 2025-07-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_goodsreception_numero_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceptiondetail',
            name='box_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.boxtype'),
        ),
        migrations.AddField(
            model_name='receptiondetail',
            name='box_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.boxtype'),
        ),
    ]
