# Generated by Django 5.2.3 on 2025-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalreceptiondetail_box_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceptiondetail',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo por caja o unidad', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalreceptiondetail',
            name='porcentaje_perdida_estimado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje estimado de pérdida para este lote', max_digits=5),
        ),
        migrations.AddField(
            model_name='receptiondetail',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo por caja o unidad', max_digits=10),
        ),
        migrations.AddField(
            model_name='receptiondetail',
            name='porcentaje_perdida_estimado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje estimado de pérdida para este lote', max_digits=5),
        ),
    ]
