# Generated by Django 5.2.3 on 2025-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalreceptiondetail_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image_path',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
