# Generated by Django 5.2.5 on 2025-08-07 03:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(choices=[('banco_estado', 'Banco Estado'), ('banco_santander', 'Banco Santander'), ('banco_chile', 'Banco de Chile'), ('banco_bci', 'Banco BCI'), ('banco_scotiabank', 'Banco Scotiabank'), ('banco_itau', 'Banco Itaú'), ('banco_security', 'Banco Security'), ('banco_falabella', 'Banco Falabella'), ('banco_ripley', 'Banco Ripley'), ('otro', 'Otro')], max_length=50, verbose_name='Banco')),
                ('otro_banco', models.CharField(blank=True, help_text='Completar solo si seleccionó "Otro" en el campo Banco', max_length=100, null=True, verbose_name='Otro Banco')),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('vista', 'Cuenta Vista'), ('ahorro', 'Cuenta de Ahorro'), ('rut', 'Cuenta RUT')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de Cuenta')),
                ('titular', models.CharField(max_length=200, verbose_name='Nombre del Titular')),
                ('rut_titular', models.CharField(max_length=20, verbose_name='RUT del Titular')),
                ('email_notificaciones', models.EmailField(help_text='Email donde se recibirán notificaciones de transferencias', max_length=254, verbose_name='Email para Notificaciones')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar para que no aparezca como opción de pago', verbose_name='Cuenta Activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Las cuentas se mostrarán ordenadas de menor a mayor', verbose_name='Orden de Visualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='business.business')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['orden', 'banco', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_view_mode', models.CharField(choices=[('standard', 'Estándar'), ('visual', 'Visual')], default='standard', help_text='Modo de vista predeterminado al abrir POS', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Configuración de negocio',
                'verbose_name_plural': 'Configuraciones de negocio',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('banco', models.CharField(choices=[('banco_estado', 'Banco Estado'), ('banco_santander', 'Banco Santander'), ('banco_chile', 'Banco de Chile'), ('banco_bci', 'Banco BCI'), ('banco_scotiabank', 'Banco Scotiabank'), ('banco_itau', 'Banco Itaú'), ('banco_security', 'Banco Security'), ('banco_falabella', 'Banco Falabella'), ('banco_ripley', 'Banco Ripley'), ('otro', 'Otro')], max_length=50, verbose_name='Banco')),
                ('otro_banco', models.CharField(blank=True, help_text='Completar solo si seleccionó "Otro" en el campo Banco', max_length=100, null=True, verbose_name='Otro Banco')),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('vista', 'Cuenta Vista'), ('ahorro', 'Cuenta de Ahorro'), ('rut', 'Cuenta RUT')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de Cuenta')),
                ('titular', models.CharField(max_length=200, verbose_name='Nombre del Titular')),
                ('rut_titular', models.CharField(max_length=20, verbose_name='RUT del Titular')),
                ('email_notificaciones', models.EmailField(help_text='Email donde se recibirán notificaciones de transferencias', max_length=254, verbose_name='Email para Notificaciones')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar para que no aparezca como opción de pago', verbose_name='Cuenta Activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Las cuentas se mostrarán ordenadas de menor a mayor', verbose_name='Orden de Visualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuenta Bancaria',
                'verbose_name_plural': 'historical Cuentas Bancarias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBusiness',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nombre', models.CharField(max_length=128)),
                ('rut', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dueno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.perfil')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Negocio',
                'verbose_name_plural': 'historical Negocios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
