# Generated by Django 5.2.3 on 2025-07-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_historicalperfil_business_and_more'),
        ('business', '0002_business_direccion_business_email_business_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_view_mode', models.CharField(choices=[('standard', 'Estándar'), ('visual', 'Visual')], default='standard', help_text='Modo de vista predeterminado al abrir POS', max_length=20)),
                ('color_theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', help_text='Tema de color para la interfaz', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Configuración de negocio',
                'verbose_name_plural': 'Configuraciones de negocio',
            },
        ),
    ]
