# Generated by Django 5.2.3 on 2025-07-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessconfig',
            name='color_theme',
        ),
    ]
