# Generated by Django 5.2.3 on 2025-07-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_configuracionusuario'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_creados', to='accounts.perfil'),
        ),
        migrations.AlterField(
            model_name='historicalannouncement',
            name='creador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.perfil'),
        ),
    ]
