# Generated by Django 5.2.3 on 2025-07-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_configuracionusuario'),
        ('announcements', '0002_alter_announcement_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementconfirmation',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_confirmados', to='accounts.perfil'),
        ),
    ]
