# Generated by Django 5.2.5 on 2025-08-07 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('anuncio', 'Anuncio'), ('sistema', 'Sistema'), ('venta', 'Venta'), ('inventario', 'Inventario'), ('turno', 'Turno'), ('stock_bajo', 'Stock Bajo'), ('venta_importante', 'Venta Importante'), ('cambio_turno', 'Cambio de Turno'), ('turno_iniciado', 'Turno Iniciado'), ('producto_nuevo', 'Producto Nuevo'), ('precio_actualizado', 'Precio Actualizado')], default='sistema', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto_relacionado_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('objeto_relacionado_id', models.CharField(blank=True, max_length=50, null=True)),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('secret_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('anuncios', models.BooleanField(default=True)),
                ('inventario', models.BooleanField(default=True)),
                ('ventas', models.BooleanField(default=True)),
                ('turnos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='business.business')),
            ],
            options={
                'unique_together': {('business', 'url')},
            },
        ),
    ]
