# Generated by Django 5.2.3 on 2025-07-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_webhooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('anuncio', 'Anuncio'), ('sistema', 'Sistema'), ('venta', 'Venta'), ('inventario', 'Inventario'), ('turno', 'Turno'), ('stock_bajo', 'Stock Bajo'), ('venta_importante', 'Venta Importante'), ('cambio_turno', 'Cambio de Turno'), ('producto_nuevo', 'Producto Nuevo'), ('precio_actualizado', 'Precio Actualizado')], default='sistema', max_length=20),
        ),
    ]
