# Generated by Django 5.2.3 on 2025-07-08 01:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='codigo_venta',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='codigo_venta',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('transbank', 'Transbank Manual'), ('credito', 'Credito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('transbank', 'Transbank Manual'), ('credito', 'Credito')], max_length=20),
        ),
    ]
